Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,7 +1,9 @@
 name: Minimal Action Implementation
 
 on: 
-  push:
+  pull_request:
+    types: [opened, synchronize]
+  push: 
     branches:
       - main
 jobs: 
@@ -9,7 +11,7 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - name: Checkout code
+      - name: Checkout repository
         uses: actions/checkout@v2
 
       - name: Set up Rust
@@ -22,13 +24,13 @@ jobs:
         run: cargo build --release
 
       - name: print
-        run: ./target/debug/fibbot
+        run: ./target/debug/fibbot ${{ github.even.inputs.input1 }} ${{ github.even.inputs.input2 }}
         
-      - name: Confirm Hello word in logs
-        run: |
-          if grep -q "Hello, world" $GITHUB_ENV; then
-            echo "Hello, world' found in logs ! "  
-          else 
-            echo "'Hello world' not found in logs"
-            exit 1
-          fi
+      # - name: Confirmation in logs
+        # run: |
+        #   if grep -q "Hello, world" $GITHUB_ENV; then
+        #     echo "Hello, world' found in logs ! "  
+        #   else 
+        #     echo "'Hello world' not found in logs"
+        #     exit 1
+        #   fi
